### ISSUE TITLE
Defaullt Implementation of IDocumentSerializer

### ISSUE THREAD

**Issue by Gentlehag** [NEventStore/NEventStore.Persistence.MongoDB#20]
Hi

is there a default implementation of the IDocumentSerializer for MongoDb integration  ?Or do i have to do it on my own?

**Comment by andreabalducci** [comment]
Just use the default DocumentObjectSerializer

            var store = Wireup.Init()
                .UsingMongoPersistence("events", new DocumentObjectSerializer())
                .InitializeStorageEngine()
                .DoNotDispatchCommits()
                .Build();
