### ISSUE TITLE
Release Updated Nuget Package

### ISSUE THREAD

**Issue by tekmaven** [NEventStore/NEventStore.Persistence.MongoDB#22]
The nuget package has not been updated since 2013.  Can it be updated?  

I can set up an AppVeyor CI build if there is interest.

**Comment by andreabalducci** [comment]
@tekmaven sorry for the delay.. that 2013 package is of the v4 version.
The right feed is http://www.nuget.org/packages/NEventStore.Persistence.MongoDB/

**Comment by andreabalducci** [comment]
@tekmaven I've created the AppVeyor CI build on a personal branch but it's too slow. Migration to internal TeamCity in progress. thank you.
