### ISSUE TITLE
Missing index on Streams collection?

### ISSUE THREAD

**Issue by CallumHibbert** [NEventStore/NEventStore.Persistence.MongoDB#23]
We have spotted an issue where some updates to the Stream collection are taking over a second to execute, sometimes more than two seconds. Example (taken from the MongoDB logs):

    2015-02-24T01:01:55.518+0000 [conn109242] update MyEventStore.Streams query: { _id: { BucketId: "default", StreamId: "145875956" } } update: { $set: { HeadRevision: 10 }, $inc: { SnapshotRevision: 0, Unsnapshotted: 4 } } nscanned:921206850 nscannedObjects:1987386870 nMatched:1 nModified:1 keyUpdates:1 numYields:0 locks(micros) w:1149905 1149ms

Please advise if an index for “BucketId” and “StreamId” should be added to the Streams collection.

Thanks.

**Comment by andreabalducci** [comment]
I think depends on the mongodb version, old versions are not too smart with indexes.
BucketId & StreamId are already indexed by default, every collection in mongodb ha a mandatory _id unique index.

Made a test on my box with mongodb 3.0rc7 and 10.000.000 streams

	{
		"op" : "update",
		"ns" : "NEvenstore.Streams",
		"query" : {
			"_id" : {
				"BucketId" : "Default",
				"StreamId" : "Test_9999541"
			}
		},
		"updateobj" : {
			"$set" : {
				"HeadRevision" : 10
			},
			"$inc" : {
				"SnapshotRevision" : 0,
				"Unsnapshotted" : 4
			}
		},
		"nscanned" : 1,
		"nscannedObjects" : 1,
		"nMatched" : 1,
		"nModified" : 1,
		"keyUpdates" : 1,
		"writeConflicts" : 0,
		"numYield" : 0,
		"millis" : 0,
		"execStats" : {},
		"ts" : ISODate("2015-05-29T10:06:11.602Z"),
		"client" : "127.0.0.1",
		"allUsers" : [],
		"user" : ""
	}
