### ISSUE TITLE
Intermittent error with Wired Tiger when there are lots of commit

### ISSUE THREAD

**Issue by alkampfergit** [NEventStore/NEventStore.Persistence.MongoDB#30]
With Wired Tiger sometimes when the system is under load this exception happens in mongo driver. It seems that something is wrong with server side script.

`System.NullReferenceException: Object reference not set to an instance of an object. at NEventStore.Persistence.MongoDB.MongoPersistenceEngine.<>c__DisplayClass19.<PersistWithServerSideOptimisticLoop>b__18() in z:\TeamCity\BuildAgent\work\9431b4b8c739449f\src\NEventStore.Persistence.MongoDB\MongoPersistenceEngine.cs:line 270 at NEventStore.Persistence.MongoDB.MongoPersistenceEngine.<>c__DisplayClass39 1.<TryMongo>b__38() in z:\TeamCity\BuildAgent\work\9431b4b8c739449f\src\NEventStore.Persistence.MongoDB\MongoPersistenceEngine.cs:line 515 at NEventStore.Persistence.MongoDB.MongoPersistenceEngine.TryMongo(Action callback) in z:\TeamCity\BuildAgent\work\9431b4b8c739449f\src\NEventStore.Persistence.MongoDB\MongoPersistenceEngine.cs:line 527 at NEventStore.Persistence.MongoDB.MongoPersistenceEngine.TryMongo[T](Func 1 callback) in z:\TeamCity\BuildAgent\work\9431b4b8c739449f\src\NEventStore.Persistence.MongoDB\MongoPersistenceEngine.cs:line 515 at NEventStore.OptimisticEventStore.Commit(CommitAttempt attempt) in c:\dev\NEventStore\src\NEventStore\OptimisticEventStore.cs:line 48 at NEventStore.OptimisticEventStream.PersistChanges(Guid commitId) in c:\dev\NEventStore\src\NEventStore\OptimisticEventStream.cs:line 189 at NEventStore.OptimisticEventStream.CommitChanges(Guid commitId) in c:\dev\NEventStore\src\NEventStore\OptimisticEventStream.cs:line 101 at `

**Comment by andreabalducci** [comment]
running server side scripts has been deprecated on new MongoDB C# Driver.
Dropped from the provider, see #19
