### ISSUE TITLE
Intermitent error when persisting stream

### ISSUE THREAD

**Issue by samuelfrancisco** [NEventStore/NEventStore.Persistence.MongoDB#34]
Sometimes is occurring the following exception. 

System.NullReferenceException
   em NEventStore.Persistence.MongoDB.MongoPersistenceEngine.<>c__DisplayClass20.<PersistWithClientSideOptimisticLoop>b__1f() na c:\TeamCity\buildAgent\work\5de2496aa2df18f5\src\NEventStore.Persistence.MongoDB\MongoPersistenceEngine.cs:linha 345
   em NEventStore.Persistence.MongoDB.MongoPersistenceEngine.<>c__DisplayClass3d`1.<TryMongo>b__3c() na c:\TeamCity\buildAgent\work\5de2496aa2df18f5\src\NEventStore.Persistence.MongoDB\MongoPersistenceEngine.cs:linha 532
   em NEventStore.Persistence.MongoDB.MongoPersistenceEngine.TryMongo(Action callback) na c:\TeamCity\buildAgent\work\5de2496aa2df18f5\src\NEventStore.Persistence.MongoDB\MongoPersistenceEngine.cs:linha 544
   em NEventStore.Persistence.MongoDB.MongoPersistenceEngine.TryMongo[T](Func`1 callback) na c:\TeamCity\buildAgent\work\5de2496aa2df18f5\src\NEventStore.Persistence.MongoDB\MongoPersistenceEngine.cs:linha 532
   em NEventStore.Persistence.MongoDB.MongoPersistenceEngine.PersistWithClientSideOptimisticLoop(CommitAttempt attempt) na c:\TeamCity\buildAgent\work\5de2496aa2df18f5\src\NEventStore.Persistence.MongoDB\MongoPersistenceEngine.cs:linha 310
   em NEventStore.Persistence.MongoDB.MongoPersistenceEngine.Commit(CommitAttempt attempt) na c:\TeamCity\buildAgent\work\5de2496aa2df18f5\src\NEventStore.Persistence.MongoDB\MongoPersistenceEngine.cs:linha 249
   em NEventStore.Persistence.PipelineHooksAwarePersistanceDecorator.Commit(CommitAttempt attempt) na c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\Persistence\PipelineHooksAwarePersistanceDecorator.cs:linha 40
   em NEventStore.OptimisticEventStore.Commit(CommitAttempt attempt) na c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\OptimisticEventStore.cs:linha 48
   em NEventStore.OptimisticEventStream.PersistChanges(Guid commitId) na c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\OptimisticEventStream.cs:linha 189
   em NEventStore.OptimisticEventStream.CommitChanges(Guid commitId) na c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\OptimisticEventStream.cs:linha 101

I think the code is hidden a mongo driver exception

**Comment by alkampfergit** [comment]
Which version of MongoDb are you using? I suspect that it could be related to the old driver and https://github.com/NEventStore/NEventStore.Persistence.MongoDB/issues/35

**Comment by samuelfrancisco** [comment]
I'm using version 3.2 of MongoDb with the old driver because NEventStore does't support the new driver yet.

**Comment by alkampfergit** [comment]
Wiredtiger or mmapv1? We have tested with mmapv1 and it usually works, but with wiredtiger sometimes there are errors.

**Comment by samuelfrancisco** [comment]
I'm using the Wiredtiger storage engine, witch was installed by default.

**Comment by alkampfergit** [comment]
This should be closed with 5.3.5 version published on myget see: https://github.com/NEventStore/NEventStore.Persistence.MongoDB/issues/35
