### ISSUE TITLE
Allow client code to specify serialization mapping for the Commit object

### ISSUE THREAD

**Issue by alkampfergit** [NEventStore/NEventStore.Persistence.MongoDB#38]
To let client code to choose how to serialize commit in mongo the simplest solution is allow client code to register IBsonSerializationProvider against a public Commit object. (http://mongodb.github.io/mongo-csharp-driver/1.11/serialization/)

This will allow for client code to have complete control over the serialization on MongoDB.

**Comment by AGiorgetti** [comment]
Closed with commit: https://github.com/NEventStore/NEventStore.Persistence.MongoDB/commit/247f5d8730b180ec03b8f638bbc77e360f9c0d5b
